---
- name: Example component
  hosts: localhost # On ResearchCloud, the target host is always simply 'localhost'.
  # vars:
    # You can define variables here.
    # One use for this is to ensure that variables expected to be passed from the SRC portal have sane defaults.
    # For example:
    # _src_component_foo: "{{ src_component_foo | default('fallback value') }}"
    # _src_component_bar: "Xone,Xtwo,Xthree"
    # _src_component_boolean: "{{ src_component_boolean | default(true, true) | bool }}"
    # But of course you can also define ordinary variables:
    # testfile: /tmp/test
    # test_pip_packages: []
  gather_facts: true

  roles:
    # - role: uusrc.general.fact_regular_users

  tasks:
    # Some example tasks below to introduce Ansible

    - name: Download SBGrid
      ansible.builtin.get_url: 
        url: https://sbgrid.org/downloads/latest/sbgrid-cli_linux.tar.gz
        dest: /tmp/sbgrid_install.tar.gz
    - name: Create SBGrid directory
      ansible.builtin.file:
        path: /usr/local/sbgrid
        owner: root
        group: root
        mode: '0755' 
        state: directory
    - name: Extract SBGrid tar file
      ansible.builtin.unarchive:
        src: /tmp/sbgrid_install.tar.gz
        dest: /usr/local/sbgrid
    - name: Install SBGrid
      ansible.builtin.command:
        cmd: /usr/local/sbgrid/sbgrid-cli activate {{license_lab}} {{license_user}} {{license_key}} --target /usr/local/sbgrid --skip-folder-checking
